---
# common setting
server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
---

# dev setting (local pc only)
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql


  datasource:
    # mysql
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/tripstory
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

# external resources location and path
resources:
  post-image:
    # for window
    # location: C:/Users/jeonseun/Desktop/TripStory_Images/Post_Images/
    # for linux
    location: /home/seun/Project/tripstory-images/post-images/
    path: /post-image
  profile:
    # for window
    # location: C:/Users/jeonseun/Desktop/TripStory_Images/Profile_Images/
    # for linux
    location: /home/seun/Project/tripstory-images/profile-images/
    path: /profile-image



---
# prod setting (google cloud platform only)
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

  cloud:
    gcp:
      sql:
        database-name: tripstory
        instance-connection-name: tripstory-283605:asia-northeast3:trip-story

  datasource:
    continue-on-error: true
    username: root
    password: tripstory1!
    initialization-mode: always

resources:
  post-image:
    path: https://storage.googleapis.com/tripstory_image/